apiVersion: v1
kind: Namespace
metadata:
    name: testserver

---
apiVersion: v1
kind: Service
metadata:
  name: simple-go
spec:
  selector:
    app: simple-go
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simple-go
spec:
  selector:
    matchLabels:
      app: simple-go
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-go
    spec:
      containers:
      - name: simple-go
        image: palson/simple-go:master
        ports:
        - containerPort: 8080

